### ISSUE TITLE
Any speed-up tips?

### ISSUE THREAD

**Issue by photonstorm** [steveush/foodoc#6]
I'm using the foodoc template on a project with just over 1000 modules in it and it takes a painfully slow time to build the html, currently just over _1 hour_. It doesn't crash, node happily carries on doing its thing and it eventually outputs all the files, but it makes doing test builds quite painful :)

Do you have any ideas on speeding it up? Maybe some node tweaks?

**Comment by steveush** [comment]
Hi,

Apologies this is so late, been side tracked with work. I'm pretty sure there are a lot of optimizations to make within the template JS, quite frankly at the moment it's a bit of a mess and it is on my TODO list however when I can get to it is another matter. I'm just happy it didn't die running on a project with over a 1000 modules :)

I've just released version 0.0.9 where I've updated all the dependencies except for lunr so there may be some speed gains from the updates to them.

Thanks
