### ISSUE TITLE
Does HTML in footer really work?

### ISSUE THREAD

**Issue by joshua-golub** [steveush/foodoc#7]
All-

The documentation defines the footer as 

> Additional content to place in the footer element of each page before the copyright and default generated by messages. This can contain HTML.

Does this actually work? I've had to luck. The HTML *markup* appears in the footer. If it *does* work, could someone point me to an example configuration for it? Maybe I am doing something wrong.

Thanks in advance for your help.

-Josh

**Comment by steveush** [comment]
Hi,

Apologies this is so late, there was an issue in the template file and it was encoding the HTML instead of simply dumping it. This is fixed in 0.0.9.

Thanks
